import type { Doctor } from "./types"

// Mock doctors database
const doctors: Doctor[] = [
  {
    id: "dr-sharma",
    name: "Dr. Anil Sharma",
    specialty: "General Medicine",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviewCount: 124,
    availability: "Mon-Fri, 9 AM - 5 PM",
    location: "New York, NY",
    isAvailableNow: true,
    bio: "Dr. Sharma has over 15 years of experience in general medicine, specializing in preventive care and chronic disease management.",
    experience: 15,
    license: "NY12345",
    contact: "doctor@example.com",
  },
  {
    id: "dr-patel",
    name: "Dr. Meena Patel",
    specialty: "Cardiology",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviewCount: 98,
    availability: "Mon, Wed, Fri, 10 AM - 6 PM",
    location: "Boston, MA",
    isAvailableNow: true,
    bio: "Dr. Patel specializes in cardiovascular health and has helped thousands of patients with heart conditions and preventive cardiology.",
    experience: 12,
    license: "MA54321",
    contact: "cardio@example.com",
  },
  {
    id: "dr-gupta",
    name: "Dr. Rajiv Gupta",
    specialty: "Orthopedics",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviewCount: 87,
    availability: "Tue-Sat, 9 AM - 3 PM",
    location: "Chicago, IL",
    isAvailableNow: false,
    bio: "Dr. Gupta is an expert in treating joint and bone conditions, chronic pain, and sports injuries using both surgical and non-surgical approaches.",
    experience: 18,
    license: "IL67890",
    contact: "bones@example.com",
  },
  {
    id: "dr-singh",
    name: "Dr. Harpreet Singh",
    specialty: "Pulmonology",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.6,
    reviewCount: 76,
    availability: "Mon-Thu, 11 AM - 7 PM",
    location: "San Francisco, CA",
    isAvailableNow: true,
    bio: "Dr. Singh specializes in respiratory conditions like asthma, COPD, and sleep apnea using evidence-based treatments.",
    experience: 10,
    license: "CA24680",
    contact: "lungs@example.com",
  },
  {
    id: "dr-reddy",
    name: "Dr. Lakshmi Reddy",
    specialty: "Dermatology",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviewCount: 112,
    availability: "Wed-Sun, 10 AM - 4 PM",
    location: "Austin, TX",
    isAvailableNow: false,
    bio: "Dr. Reddy is renowned for her expertise in treating various skin conditions using both traditional and cutting-edge approaches.",
    experience: 14,
    license: "TX13579",
    contact: "skin@example.com",
  },
  {
    id: "dr-joshi",
    name: "Dr. Vikram Joshi",
    specialty: "Psychiatry",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.9,
    reviewCount: 65,
    availability: "Mon, Wed, Fri, 12 PM - 8 PM",
    location: "Seattle, WA",
    isAvailableNow: true,
    bio: "Dr. Joshi combines modern psychiatry with holistic approaches to help patients with anxiety, depression, and stress-related disorders.",
    experience: 16,
    license: "WA97531",
    contact: "mind@example.com",
  },
  {
    id: "dr-verma",
    name: "Dr. Sunita Verma",
    specialty: "Gastroenterology",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.7,
    reviewCount: 91,
    availability: "Tue-Sat, 9 AM - 5 PM",
    location: "Denver, CO",
    isAvailableNow: false,
    bio: "Dr. Verma specializes in treating IBS, GERD, and other digestive disorders using evidence-based methods.",
    experience: 13,
    license: "CO86420",
    contact: "gut@example.com",
  },
  {
    id: "dr-kumar",
    name: "Dr. Arjun Kumar",
    specialty: "Endocrinology",
    image: "/placeholder.svg?height=200&width=200",
    rating: 4.8,
    reviewCount: 104,
    availability: "Mon-Fri, 10 AM - 6 PM",
    location: "Atlanta, GA",
    isAvailableNow: true,
    bio: "Dr. Kumar has helped hundreds of patients manage diabetes, thyroid disorders, and other hormonal conditions through personalized care plans.",
    experience: 20,
    license: "GA75319",
    contact: "hormones@example.com",
  },
]

export function getDoctors() {
  return doctors
}

export function getDoctorById(id: string) {
  return doctors.find((doctor) => doctor.id === id)
}

